export const actions = {
  VALIDATE_CONVERSATION: "VALIDATE_CONVERSATION",
  VALIDATE_CONVERSATION_SUCCESS: "VALIDATE_CONVERSATION_SUCCESS",
  VALIDATE_CONVERSATION_FAIL: "VALIDATE_CONVERSATION_FAIL",
  START_CONVERSATION: "START_CONVERSATION",
  START_CONVERSATION_SUCCESS: "START_CONVERSATION_SUCCESS",
  START_CONVERSATION_FAIL: "START_CONVERSATION_FAIL",
  SEND_MESSAGE: "SEND_MESSAGE",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_FAIL: "SEND_MESSAGE_FAIL",
  UPDATE_MESSAGE: "UPDATE_MESSAGE",
  SET_USER_SELECTED_REAL_TIME_INFO: "SET_USER_SELECTED_REAL_TIME_INFO",
  ADD_MESSAGE_RECEIVED: "ADD_MESSAGE_RECEIVED",
};
