export const actions = {
    SET_NEXT_QUESTION: 'SET_NEXT_QUESTION',
    IS_FINISHED: 'IS_FINISHED',
    ADD_LEARNING_VISUAL: 'ADD_LEARNING_VISUAL',
    ADD_LEARNING_AUDITIVO: 'ADD_LEARNING_AUDITIVO',
    ADD_LEARNING_KINESTESICO: 'ADD_LEARNING_KINESTESICO',
    SET_LEARNING_FINAL: 'SET_LEARNING_FINAL',
    REGISTER_LEARNING_REQUEST: 'REGISTER_LEARNING_REQUEST',
    REGISTER_LEARNING_SUCCESS: 'REGISTER_LEARNING_SUCCESS',
    REGISTER_LEARNING_FAILURE: 'REGISTER_LEARNING_FAILURE',
};
