export const actions = {
  UPDATE_FORM_DATA: "UPDATE_FORM_DATA",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "LOGIN_FAILURE",
  SET_ERRORS: "SET_ERRORS",
  SET_STEP: "SET_STEP",
};
