export const actions = {
  SET_SELECTED_USER: "SET_SELECTED_USER",
  SET_USER_DATA_SOCKET: "SET_USER_DATA_SOCKET",
  USER_TEST_REQUEST: "USER_TEST_REQUEST",
  USER_TEST_SUCCESS: "USER_TEST_SUCCESS",
  USER_TEST_FAILURE: "USER_TEST_FAILURE",
};
